# Generated by Django 3.1.4 on 2022-07-25 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('mcserver', '0004_auto_20220701_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmed_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_user', to='authtoken.token'),
        ),
    ]
