# Generated by Django 3.1.4 on 2022-07-25 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcserver', '0005_user_confirmed_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirmed_token',
        ),
        migrations.AddField(
            model_name='user',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
