# Generated by Django 3.1.14 on 2022-10-12 21:55

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mcserver', '0007_user_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPassword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('datetime', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
