# Generated by Django 3.1.14 on 2022-11-17 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otp_email', '0004_throttling'),
        ('mcserver', '0008_resetpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomEmailDevice',
            fields=[
                ('emaildevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='otp_email.emaildevice')),
            ],
            options={
                'abstract': False,
            },
            bases=('otp_email.emaildevice',),
        ),
    ]
