# Generated by Django 3.1.14 on 2023-02-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcserver', '0009_customemaildevice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='session',
            name='trashed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='trashed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
