# Generated by Django 3.2.16 on 2023-02-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcserver', '0011_auto_20230203_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profesion',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
