# Generated by Django 3.1.14 on 2023-02-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcserver', '0010_auto_20230202_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='trashed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trial',
            name='trashed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
