# Generated by Django 3.2.16 on 2023-02-02 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcserver', '0011_auto_20230203_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profesion',
            new_name='profession',
        ),
    ]
