# Generated by Django 3.1.14 on 2023-03-28 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcserver', '0013_user_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('weight', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Weight (kg)')),
                ('height', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Weight (m)')),
                ('age', models.IntegerField(blank=True, default=0.0, null=True, verbose_name='Weight (y)')),
                ('gender', models.CharField(blank=True, choices=[('woman', 'Woman'), ('man', 'Man'), ('transgender', 'Transgender'), ('non-binary', 'Non-Binary/Non-Conforming'), ('prefer-not-respond', 'Prefer Not to Respond')], max_length=20, null=True)),
                ('sex_at_birth', models.CharField(blank=True, choices=[('woman', 'Woman'), ('man', 'Man'), ('intersect', 'Intersect'), ('not-listed', 'Not Listed'), ('prefer-not-respond', 'Prefer Not to Respond')], max_length=20, null=True)),
                ('characteristics', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trashed', models.BooleanField(default=False)),
                ('trashed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
    ]
