# Generated by Django 3.1.14 on 2023-03-28 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcserver', '0011_auto_20230203_1355'),
        ('mcserver', '0011_rename_profesion_user_profession'),
    ]

    operations = [
    ]
