# Generated by Django 3.1.14 on 2023-03-28 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcserver', '0012_merge_20230328_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
