# Generated by Django 3.1.14 on 2023-03-31 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcserver', '0012_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='mcserver.subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='age',
            field=models.IntegerField(blank=True, default=0.0, null=True, verbose_name='Age (y)'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='height',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Height (m)'),
        ),
    ]
