# Generated by Django 3.1.14 on 2023-05-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcserver', '0013_auto_20230331_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_skip_till',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
