# Generated by Django 3.1.14 on 2023-06-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcserver', '0016_downloadlog_optional_user_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='birth_year',
            field=models.PositiveIntegerField(blank=True, help_text='Use the following format: <YYYY>', null=True, verbose_name='Birth year'),
        ),
    ]
