# Generated by Django 3.1.14 on 2023-06-20 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcserver', '0016_downloadlog_optional_user_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisFunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('url', models.URLField(max_length=255, verbose_name='Url')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, verbose_name='Celery task id.')),
                ('data', models.JSONField(default=dict, help_text='Data function was called with.', verbose_name='Data')),
                ('result', models.JSONField(default=dict, help_text='Data function responsed with.', verbose_name='Result')),
                ('status', models.IntegerField(default=200, help_text='Status code function responsed with.', verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcserver.analysisfunction', verbose_name='Analysis function')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
