# Generated by Django 3.1.14 on 2023-06-13 08:25

from django.db import migrations
from django.utils import timezone


def populate_birth_year_from_age(apps, schema_editor):
    Subject = apps.get_model('mcserver', 'Subject')
    for subject in Subject._default_manager.all():
        if subject.age:
            subject.birth_year = timezone.now().year - subject.age
            subject.save(update_fields=['birth_year'])


class Migration(migrations.Migration):

    dependencies = [
        ('mcserver', '0017_subject_birth_year_field'),
    ]

    operations = [
        migrations.RunPython(populate_birth_year_from_age, migrations.RunPython.noop),
    ]
