# Generated by Django 3.1.14 on 2023-06-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcserver', '0018_analysisfunction_choice_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisfunction',
            name='url',
            field=models.CharField(max_length=255, verbose_name='Url'),
        ),
    ]
