# Generated by Django 3.1.14 on 2023-09-26 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcserver', '0023_analysisresult_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisfunction',
            name='local_run',
            field=models.BooleanField(default=False, help_text='Use this option if you debug the function locally with AWS RIE, due the different way of passing data to the function.', verbose_name='Local run'),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='trial',
            field=models.ForeignKey(blank=True, help_text='Trial function was called with. Set automatically.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_results', to='mcserver.trial', verbose_name='Trial'),
        ),
        migrations.CreateModel(
            name='AnalysisDashboardTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('layout', models.JSONField(default=dict, verbose_name='Layout')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_templates', to='mcserver.analysisfunction', verbose_name='Analysis function')),
            ],
            options={
                'verbose_name': 'Analysis dashboard template',
                'verbose_name_plural': 'Analysis dashboard templates',
                'ordering': ['title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisDashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('layout', models.JSONField(default=dict, verbose_name='Layout')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='mcserver.analysisfunction', verbose_name='Analysis function')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboards', to='mcserver.analysisdashboardtemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analysis dashboard',
                'verbose_name_plural': 'Analysis dashboards',
                'ordering': ['title', 'id'],
            },
        ),
    ]
