# Generated by Django 3.1.14 on 2023-10-03 08:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcserver', '0024_auto_20230926_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisfunction',
            name='only_for_users',
            field=models.ManyToManyField(blank=True, related_name='analysis_functions', to=settings.AUTH_USER_MODEL),
        ),
    ]
