# Generated by Django 3.1.14 on 2023-12-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcserver', '0025_analysisfunction_only_for_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='institutional_use',
            field=models.CharField(blank=True, choices=[('', 'Not specified'), ('patient_care', 'Patient care'), ('sports_performance_assessment', 'Sports performance assessment'), ('use_in_company', 'Use in a company or in collaboration with a company'), ('research_at_academic', 'Research at an academic institution'), ('teaching_at_academic', 'Teaching at an academic institution'), ('other_non_commercial', 'Other non-commercial activity')], default='', max_length=100),
        ),
    ]
