# Generated by Django 3.1.14 on 2024-01-23 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mcserver', '0027_auto_20240105_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.CharField(blank=True, db_index=True, default='init', max_length=64),
        ),
        migrations.AddField(
            model_name='session',
            name='status_changed',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True),
        ),
    ]
