# Generated by Django 4.2 on 2024-02-08 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mcserver", "0030_rename_tags_subject_subject_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="subject_tags",
        ),
        migrations.CreateModel(
            name="SubjectTags",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.TextField()),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mcserver.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["subject", "tag"],
            },
        ),
    ]
