# Generated by Django 3.1.14 on 2024-03-19 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcserver', '0029_analysisfunction_info'),
        ('mcserver', '0031_remove_subject_subject_tags_subjecttags'),
    ]

    operations = [
    ]
