# Generated by Django 3.1.14 on 2024-04-09 18:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mcserver', '0033_auto_20240319_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.CharField(blank=True, db_index=True, default='init', max_length=64),
        ),
        migrations.AddField(
            model_name='session',
            name='status_changed',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True),
        ),
    ]
