# Generated by Django 3.1.14 on 2024-05-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcserver', '0034_auto_20240409_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisdashboard',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
