# Generated by Django 3.2 on 2024-09-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcserver', '0036_auto_20240919_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='git_commit',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
