# Generated by Django 4.2 on 2024-10-08 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mcserver", "0034_alter_analysisresult_status_trialtags"),
        ("mcserver", "0038_alter_analysisresult_status"),
    ]

    operations = []
