# Generated by Django 4.2.22 on 2025-06-05 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcserver', '0040_session_is_mono_alter_subject_sex_at_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='is_mono',
        ),
    ]
