# Generated by Django 4.2.22 on 2025-06-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcserver', '0041_remove_session_is_mono'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='isMono',
            field=models.BooleanField(default=False),
        ),
    ]
