# Generated by Django 4.2.22 on 2025-06-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcserver', '0042_session_ismono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='isMono',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
