# Generated by Django 3.1.14 on 2026-06-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcserver', '0045_video_islidar'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='save_local',
            field=models.BooleanField(default=False),
        ),
    ]
