# Generated by Django 3.1.14 on 2026-06-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcserver', '0046_session_save_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='saved_local',
            field=models.BooleanField(default=False),
        ),
    ]
