# Generated by Django 3.1.14 on 2026-06-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mcserver", "0047_video_saved_local"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="saved_local",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
