# Generated by Django 3.1.14 on 2026-06-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcserver', '0048_video_saved_local_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='useLidar',
            field=models.BooleanField(default=False),
        ),
    ]
