# Generated by Django 3.1.4 on 2020-12-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcserver', '0002_auto_20201211_0444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='session',
            new_name='trial',
        ),
        migrations.AddField(
            model_name='trial',
            name='status',
            field=models.CharField(default='recording', max_length=32),
        ),
    ]
