# Generated by Django 3.1.4 on 2020-12-11 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcserver', '0003_auto_20201211_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='trial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcserver.trial', db_index=False),
        ),
    ]
