# Generated by Django 3.1.4 on 2020-12-11 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcserver', '0005_auto_20201211_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_thumb',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
