# Generated by Django 3.1.4 on 2020-12-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcserver', '0006_auto_20201211_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='device_id',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
