# Generated by Django 3.1.4 on 2020-12-12 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcserver', '0007_video_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='qrcode',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
