# Generated by Django 3.1.4 on 2020-12-12 04:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mcserver', '0008_session_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
