# Generated by Django 3.1.4 on 2020-12-14 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcserver', '0009_auto_20201212_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='keypoints',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='video',
            name='parameters',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
