# Generated by Django 3.1.4 on 2021-04-07 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcserver', '0011_auto_20210316_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='meta',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
