# Generated by Django 3.1.4 on 2021-09-25 21:36

from django.db import migrations, models
import mcserver.models


class Migration(migrations.Migration):

    dependencies = [
        ('mcserver', '0012_session_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='device_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=mcserver.models.random_filename),
        ),
        migrations.AlterField(
            model_name='result',
            name='json',
            field=models.FileField(blank=True, null=True, upload_to=mcserver.models.random_filename),
        ),
        migrations.AlterField(
            model_name='result',
            name='trc',
            field=models.FileField(blank=True, null=True, upload_to=mcserver.models.random_filename),
        ),
    ]
