# Generated by Django 3.1.4 on 2021-10-02 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcserver', '0013_auto_20210925_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='json',
        ),
        migrations.RemoveField(
            model_name='result',
            name='trc',
        ),
        migrations.AddField(
            model_name='result',
            name='tag',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
