# Generated by Django 3.1.4 on 2022-01-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcserver', '0014_auto_20211002_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='server',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='meta',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
