# Generated by Django 3.1.4 on 2022-04-18 20:00

from django.db import migrations, models
import mcserver.models


class Migration(migrations.Migration):

    dependencies = [
        ('mcserver', '0015_auto_20220126_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='media',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=mcserver.models.random_filename),
        ),
        migrations.AlterField(
            model_name='session',
            name='server',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
