# Generated by Django 3.1.4 on 2022-04-21 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcserver', '0017_auto_20220421_0521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='status',
            new_name='institution',
        ),
    ]
