# Generated by Django 3.1.4 on 2022-04-25 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcserver', '0018_auto_20220421_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
