# Generated by Django 3.1.4 on 2022-05-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcserver', '0019_auto_20220425_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
